config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get 'about', to:'pages#about'
  resources :employees
  get 'empdelete/:id', to:'employees#destroy', as: :empdelete
  #resources :employees, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

# 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, presence: true, length:{minimum:2, maximum:100}
    validates :city, presence: true,length:{minimum:2, maximum:50}
    validates :tech, presence: true,length:{minimum:2, maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
   
    def destroy
        
        @employee=Employee.find(params[:id])
        @employee.destroy
        redirect_to employees_path
    end

    def show
        @employee=Employee.find(params[:id])
    end













    def edit
        @employee=Employee.find(params[:id])
    end

    def update
        @employee = Employee.find(params[:id])
        if @employee.update(params.require(:employee).permit(:name,:city,:tech))
            flash[:notice]="Employee updated successfully."
            redirect_to @employee
        else
            render 'edit'
        end
    end








    def index
        @employees=Employee.all 
    end

    def new
        @employee=Employee.new
    end

    def create
      @employee = Employee.new(params.require(:employee).permit(:name,:city,:tech))
      
      if @employee.save
        flash[:notice]="Employee details was created successfully."
        redirect_to employee_path(@employee)
      else
        render 'new'
      end

    end

    


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<h1>Update Employee</h1>

<% if @employee.errors.any? %>
    <h2>The following errors prevented the article from being saved </h2>
    
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
    <% end %>
    </ul>
<% end %>


<%= form_with(model:@employee, local: true) do |f| %>

<p>
    <%= f.label :name%>
    <br>
    <%= f.text_field :name%>
</p>

<p>
    <%= f.label :city%>
    <br>
    <%= f.text_field :city%>
</p>

<p>
    <%= f.label :tech%>
    <br>
    <%= f.text_field :tech%>
</p>

<p>
    <%= f.submit%>
</p>


<% end %>

<%= link_to 'Cancel and Return to employee listing', employees_path%>

app/views/employees/index.html.erb
<h1> Employees Listing Page!!!</h1>

<br>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>City</th>
            <th>Tech</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>

    <tbody>
    <% @employees.each do |employee| %>
        <tr>
            <td><%= employee.name%></td>
            <td><%= employee.city%></td>
            <td><%= employee.tech%></td> 
            <td><%= link_to 'Show', employee_path(employee.id)%></td>
            <td><%= link_to 'Edit', edit_employee_path(employee.id)%></td>
            <td><%= link_to 'Delete', empdelete_path(employee.id), data: { turbo_confirm: "Are you sure?" } , method: :delete %> </td>
        </tr>
    <%  end %>   
    </tbody>
</table>
<p>
<%= link_to 'Add New Employee', new_employee_path %>
</p>

app/views/employees/new.html.erb
<h1>Create a new Employee</h1>

<% if @employee.errors.any? %>
    <h2>The following errors prevented the article from being saved </h2>
    
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
    <% end %>
    </ul>
<% end %>


<%= form_with scope: :employee, url: employees_path, local: true ,data: { turbo: false } do |f| %>

<p>
    <%= f.label :name%>
    <br>
    <%= f.text_field :name%>
</p>

<p>
    <%= f.label :city%>
    <br>
    <%= f.text_field :city%>
</p>

<p>
    <%= f.label :tech%>
    <br>
    <%= f.text_field :tech%>
</p>

<p>
    <%= f.submit%>
</p>


<% end %>

<%= link_to 'Return to employee listing', employees_path%>

app/views/employees/show.html.erb
<h1> Showing Employees Details</h1>
<br>
<p> <strong>Name: </strong><%= @employee.name%></p>
<p> <strong>City: </strong><%=@employee.city%></p>
<p> <strong>Tech: </strong><%= @employee.tech%></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Delete', empdelete_path(@employee.id), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to employee listing', employees_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <% flash.each do |name, msg|%>
    <%=msg%>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello in About Us Page </h1>
<%= link_to 'See Employees List', employees_path%> |
<%= link_to 'Home Page', root_path%>

app/views/pages/home.html.erb
<h1>Welcome to simform Page</h1>
<%= link_to 'See Employees List', employees_path%> |
<%= link_to 'About US', about_path%>